site_name: etrack

repo_url: https://github.com/bendalab/etrack/

edit_uri: ""

site_author: Jan Grewe jan.grewe@g-node.org

theme: readthedocs
    
nav:
    - Home: 'introduction.md'
    - 'Getting started':
        - 'etrack': 'introduction.md'
        - 'TrackingData' : 'trackingdata.md'
    - 'Code':
        - API reference: 'api/index.html'